version: '3'
services:
  db:
    image: "postgres:9.5"
    volumes:
     - ./database:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    env_file:
     - discuss.env
    container_name: discuss_db
